apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: warvba22/ollama:10.1 # Replace with desired Ollama image tag
        ports:
        - containerPort: 11434
        
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
spec:
  type: NodePort  # This line makes the service accessible via NodePort
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
    nodePort: 30000  # Optional: specify the node port (must be between 30000-32767)
