apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: warvba22/ollama:10.1 # Replace with desired Ollama image tag
        ports:
        - containerPort: 11434

        
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
  - protocol: TCP
  - nodePort: 30005       # Choose a port within the 30005-30010 range
    port: 11434          # The port that the service will expose
    targetPort: 11434    # The port on the container that the service should forward traffic to
  type: NodePort  


  # The port on the node that you want to use for the service

